config/routes.rb
Rails.application.routes.draw do
  get '/pages/emergency_form', to: 'pages#emergency_form'
  get '/pages/loading_page', to: 'pages#loading_page'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # config/routes.rb
  devise_scope :user do
    get 'select_role', to: 'users/registrations#select_role'
  end
  get '/users/registrations/user', to: 'users/registrations#user'
  get '/users/registrations/volunteer', to: 'users/registrations#volunteer'
  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  resources :forum_threads do
    resources :forum_posts, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :user
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
  belongs_to :user
  has_many :forum_posts, dependent: :destroy

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
  validates_associated :forum_posts
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :forum_threads
  has_many :forum_posts
  has_many :comments
  def assign_default_role
    add_role(:default) if roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization
end

app/controllers/forum_posts_controller.rb
class ForumPostsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @forum_thread = ForumThread.find(params[:forum_thread_id])
    @forum_post = @forum_thread.forum_posts.build(forum_post_params)
    @forum_post.user = current_user

    if @forum_post.save
      redirect_to @forum_thread, notice: 'Post was successfully created.'
    else
      redirect_to @forum_thread, alert: 'There was an error creating your post.'
    end
  end

  private

  def forum_post_params
    params.require(:forum_post).permit(:body)
  end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_forum_thread, except: %i[index new create]

  def index
    @forum_threads = ForumThread.all
  end

  def show
    @forum_thread = ForumThread.find(params[:id])
    @forum_post = ForumPost.new
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.build
  end

  def create
    @forum_thread = current_user.forum_threads.build(forum_thread_params)
    @forum_thread.forum_posts.first.user_id = current_user.id
    if @forum_thread.save
      redirect_to @forum_thread, notice: 'Thread was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @forum_thread # verifica se o usuário tem permissão para editar o tópico
    @forum_thread.forum_posts.build if @forum_thread.forum_posts.empty? # cria um novo post vazio se o tópico não tiver nenhum
  end

  def update
    @forum_thread = ForumThread.find(params[:id])

    if request.patch? && params[:commit] == "Update Forum thread"
      if @forum_thread.update(forum_thread_params)
        respond_to do |format|
          format.turbo_stream # Atualiza a parte da página que exibe o tópico
          format.html { redirect_to @forum_thread, notice: 'Thread was successfully updated.' }
        end
      else
        render :edit
      end
    end
  end


  def destroy
    authorize @forum_thread # verifica se o usuário tem permissão para deletar o tópico
    @forum_thread.destroy # remove o tópico e os posts associados do banco de dados
    redirect_to forum_threads_path, notice: 'Thread was successfully deleted.' # redireciona para a página de índice dos tópicos com uma mensagem de sucesso
  end

  private

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end

  def forum_thread_params
    params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body, :id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :emergency_form, :loading_page]

  def home
  end

  def emergency_form
  end

  def loading_page
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # POST /resource
  def create
    super
    resource.add_role(params[:user][:roles])
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :phone, :city, :state, :country, :address, :instagram, :profession, :professional_registration, :specialty, roles: []])
  end
end

app/controllers/users/registrations_controller.rb
# app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def select_role
    chose_volunteer = params[:role_id] == Role.find_by(name: 'volunteer').id.to_s
    session[:chose_volunteer] = chose_volunteer
    #redirect_to new_user_registration_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to users_path
  end

  def select_role
    chose_volunteer = params[:chose_volunteer] == 'true'
    session[:chose_volunteer] = chose_volunteer

    if chose_volunteer
      redirect_to new_volunteer_registration_path
    else
      redirect_to new_user_registration_path
    end
  end


  def create
    super do |resource|
      if params[:user_role] == 'volunteer'
        resource.add_role(:volunteer)
      else
        resource.add_role(:user)
      end
    end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :age, :phone, :city, :state, :country, :address, :instagram, :profession, :professional_registration, :specialty, role_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_threads/_form.htm.erb
<%= form_for forum_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>

  <%= f.fields_for :forum_posts do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_threads/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center mt-4 mb-4">New Thread</h1>


      <%= form_for @forum_thread do |f| %>
        <div class="form-group my-1">

          <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
        </div>

        <%= f.fields_for :forum_posts do |p| %>
          <div class="form-group">

            <%= p.text_area :body, placeholder: "Add a comment", rows: 5, class: "form-control" %>
          </div>
        <% end %>

        <%= link_to 'Back', forum_threads_path, class: "btn btn-secondary mb-4" %>
        <div class="form-group">

          <%= f.submit "Create Thread", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/forum_threads/edit.html.erb
<h1>Edit Thread</h1>
<%= form_for @forum_thread, method: :patch, data: { turbo: false } do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>

  <%= f.fields_for :forum_posts, @forum_thread.forum_posts.first do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit "Update Forum thread", name: "commit" %>
  </div>
<% end %>
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Forum Threads</h1>
    <%= link_to 'New Thread', new_forum_thread_path, class: "btn btn-success" %>
  </div>

  <% @forum_threads.each do |thread| %>
    <div class="thread">
      <h2><%= link_to thread.subject, forum_thread_path(thread) %></h2>
      <p>Started by: <%= thread.user.email %></p>
      <%= link_to 'Edit', edit_forum_thread_path(thread), class: "btn btn-primary" %>
      <%= link_to "Delete", forum_thread_path(thread), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/forum_threads/new.html.erb
<%= render 'form', locals: { forum_thread: @forum_thread } %>

app/views/forum_threads/show.html.erb
<div class="container">
<h1><%= @forum_thread.subject %></h1>

<% @forum_thread.forum_posts.each_with_index do |post, index| %>
  <div class="<%= index == 0 ? 'first-post' : 'normal-post' %>">
    <p><%= post.body %></p>
    <p>Postado por <%= post.user.email %> </p>
  </div>
<% end %>

<h2>Responder</h2>

<%= form_for [@forum_thread, ForumPost.new] do |f| %>
  <%= f.label :body, "Resposta" %><br>
  <%= f.text_area :body %><br>
  <%= f.submit "Postar Resposta" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acolhimente</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/pages/emergency_form.html.erb
    <div class="container my-5 h-100 w-100 d-flex justify-content-center align-items-center">
<div class="card card-emergency">
  <div class="card-body">
    <h5 class="card-title text-center my-4 mt-0">Formulário de emergência</h5>
    <h6 class="card-subtitle mb-2 text-center">Preencha os campos abaixo para darmos continuidade ao seu atendimento.</h6>
      <%= form_with(url: 'emergency_form', local: true) do |form| %>
      <div class="form-group text-center">
        <%= form.label :idade, class: 'h4 my-2' %>
        <%= form.number_field :idade, class: 'form-control rounded-pill w-50 m-auto', min: 0, max:99 %>
      </div>
      <br>
      <div class="form-group">
        <p class='h4 text-center'>Como deseja conversar?</p>
        <div class="form-check">
          <%= form.radio_button :opcao, 'texto', class: 'form-check-input' %>
          <%= form.label :opcao_audio, 'Texto', class: 'form-check-label' %>
        </div>
        <div class="form-check">
          <%= form.radio_button :opcao, 'audio', class: 'form-check-input' %>
          <%= form.label :opcao_audio, 'Áudio', class: 'form-check-label' %>
        </div>
        <div class="form-check">
          <%= form.radio_button :opcao, 'video_chamada', class: 'form-check-input' %>
          <%= form.label :opcao_video_chamada, 'Vídeo Chamada', class: 'form-check-label' %>
        </div>
        <br>
        <div class="d-flex m-auto justify-content-center send-emergency-button">
      <%= form.submit 'Enviar', class: 'btn text-button-color-emergency' %>
      </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container d-flex align-items-center justify-content-center col-6 my-4">
  <div class="text-center">
  <h1> <strong>Você não está sozinho</strong></h1>
    <strong><p class="my-4">Que bom que você chegou!
      Nós estamos aqui, prontos
      para te escutar e apoiar
      neste momento difícil.
    </p></strong>
    <div class="d-flex justify-content-center my-4">
      <%= link_to "SOS", pages_emergency_form_path, class: "sos-btn" %>
    </div>
    <strong><p class="my-5">Sente que está muito pesado? Vamos conversar, estamos aqui por você!</p></strong>
  </div>
</div>

<footer> <%= image_tag "abraco.jpg", class: "footer-image img-fluid" %></div> </footer>

app/views/pages/loading_page.erb
<div class="container d-flex align-items-center justify-content-center">
  <div class="text-center">
  <br>
    <p>Você não está sozinho.</p>
    <p> Nós estamos aqui por você.</p>
    <p>Por favor, aguarde um momento enquanto buscamos alguém para te ajudar.</p>
    <br>
    <div class="c-loader container"></div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand mx-2" href="<%= root_path %>">
      <img src="https://i.postimg.cc/B8ChJ612/Screenshot-2023-11-01-102008.png" />
    </a>
    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-controller="nav">
      <img class="hamburger" src="https://i.postimg.cc/ct8wLxJs/Screenshot-2023-11-01-104315.png" alt="Toggle navigation" data-action="click->nav#toggleCollapsedMenuColor">
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
      <ul class="navbar-nav me-auto">
          <li class="nav-item active mx-2">
            <%= link_to "Forum", forum_threads_path, class: "nav-link nav-text" %>
          </li>
          <li class="nav-item active mx-2">
           <%= link_to 'Home', root_path, class: 'nav-link nav-text' %>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link nav-text" href="#"><strong></strong>Messages</a>
          </li>
          <li class="nav-item dropdown mx-2 d-none d-md-block">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <%= link_to "Sair", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              <%= link_to "Login/SignUp", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

<script>
  // Function to toggle the custom class on the collapsed menu
  function toggleCollapsedMenuColor() {
    const collapsedMenu = document.querySelector('.navbar-collapse');
    collapsedMenu.classList.toggle('collapse-menu');
  }

  // Add a click event listener to the hamburger button
  document.querySelector('.navbar-toggler').addEventListener('click', toggleCollapsedMenuColor);
</script>

app/views/users/edit.html.erb
<div class="mt-5">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.collection_check_boxes :role_ids, Role.all, :id, :name,
          required: false,
          input_html: { class: 'form-control' } %>
    </div>

    <div class="form-actions mt-3">
      <%= f.button :submit, class: 'btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>USERS</h1>
<% @users.each do |user|%>
  <p><%= user.email %></p>
  <%= user.roles.pluck(:name) %> <br>
  <%= link_to 'Edit Roles', edit_user_path(user), class: 'btn btn-outline-dark'%>
<% end %>